<a href="https://colab.research.google.com/github/abdelhalimyasser/Olympics-Data-Pipeline-AI-Classification/blob/main/notebooks/dashboard_graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy matplotlib seaborn plotly_express dash

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: plotly_express in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: dash in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: plotly>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from plotly_express) (5.24.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from plotly_express) (0.14.6)
Requirement already satisfied: scipy>=0.18 in /usr/local/lib/python3.12/dist-packages (from plotly_express) (1.16.3)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.12/dist-packages (from plotly_express) (1.0.2)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash) (8.7.1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dash) (2.32.4)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash) (75.2.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.0.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.1.0->plotly_express) (9.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2026.2.25)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from dash import Dash, html, dcc

In [ ]:
discontinued_sports_df = pd.read_csv('discontinued_sports.csv')
discontinued_sports_df.head()

,season,discipline,contest_year,number_of_olympics,gold_medals,silver_medals,bronze_medals
0,Summer,Basque pelota,1900,1,1,0,0
1,Summer,Breaking,2024,1,2,2,2
2,Summer,Croquet,1900,1,3,2,2
3,Summer,Jeu de paume,1908,1,1,1,1
4,Summer,Karate,2020,1,8,8,16

In [ ]:
medalists_age_df = pd.read_csv('medalists_age.csv')
medalists_age_df.head()

,medalist,age,sport,title,details
0,Ailing Eileen Gu,18.43,Freestyle skiing,Youngest freestyle skiing medalist,NaN
1,Ailing Eileen Gu,18.43,Freestyle skiing,Youngest freestyle skiing gold medalist,NaN
2,Ailing Eileen Gu,18.43,Freestyle skiing,Youngest female freestyle skiing medalist,NaN
3,Ailing Eileen Gu,18.43,Freestyle skiing,Youngest female freestyle skiing gold medalist,"At the 2022 Winter Olympics , Ailing Eileen Gu..."
4,Dara Torres,41.00,Swimming,Oldest swimming medalist,Torres won silver for the women's 4x100 freest...

In [ ]:
olympiad_summry_df = pd.read_csv('olympiad_summry.csv')
olympiad_summry_df.head()

,season,games_year,host_city,host_country,total_events,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total_medals,athlete_with_most_medals,athlete_with_most_medals_country,athlete_with_most_gold_medals,athlete_with_most_gold_medals_country
0,Summer,1896,Athens,Greece,43,43,43,36,122,Hermann Weingärtner,GER,Carl Schuhmann,GER
1,Summer,1964,Tokyo,Japan,163,163,167,174,504,Larisa Latynina,URS,Don Schollander,USA
2,Summer,1952,Helsinki,Finland,149,149,152,158,459,Maria Gorokhovskaya,URS,Viktor Chukarin,URS
3,Summer,1968,Mexico City,Mexico,172,174,170,183,527,Mikhail Voronin,URS,Věra Čáslavská,TCH
4,Summer,1972,Munich,West Germany,195,195,195,210,600,Mark Spitz,USA,Mark Spitz,USA

In [ ]:
sports_summry_df = pd.read_csv('sports_summry.csv')
sports_summry_df.head()

,season,discipline,number_of_olympics,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total_medals,athlete_with_most_medals,athlete_with_most_gold_medals
0,Summer,Archery,18,76,74,66,216,Hubert van Innis,Hubert van Innis
1,Summer,Rowing,29,282,282,286,850,Elisabeta Lipă,Elisabeta Lipă
2,Summer,Rugby,7,10,11,7,28,Theresa Fitzpatrick,Theresa Fitzpatrick
3,Summer,Sailing,29,205,197,190,592,Ben Ainslie,Ben Ainslie
4,Summer,Shooting,28,302,303,301,906,Carl Osburn,Carl Osburn

In [ ]:
fig = px.bar(
    discontinued_sports_df,
    x='contest_year',
    y='number_of_olympics',
    title='Number of Olympics per Contest Year for Discontinued Sports',
    labels={'contest_year': 'Contest Year', 'number_of_olympics': 'Number of Olympics'}
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Contest Year',
    yaxis_title='Number of Olympics'
)

fig.show()

In [ ]:
discontinued_sports_melted = discontinued_sports_df.melt(
    id_vars=['discipline'],
    value_vars=['gold_medals', 'silver_medals', 'bronze_medals'],
    var_name='medal_type',
    value_name='medal_count'
)

color_map = {
    'gold_medals': 'orange',
    'silver_medals': 'gray',
    'bronze_medals': 'brown'
}
discontinued_sports_melted['color'] = discontinued_sports_melted['medal_type'].map(color_map)

fig = px.bar(
    discontinued_sports_melted,
    x='discipline',
    y='medal_count',
    color='medal_type',
    color_discrete_map=color_map,
    title='Medal Distribution for Discontinued Sports',
    labels={'discipline': 'Discipline', 'medal_count': 'Number of Medals', 'medal_type': 'Medal Type'},
    barmode='group'
)

fig.update_layout(
    xaxis_tickangle=-45,
    legend_title_text='Medal Type',
    xaxis_title='Discipline',
    yaxis_title='Number of Medals'
)

fig.show()

In [ ]:
fig = px.bar(
    medalists_age_df,
    x='sport',
    y='age',
    title='Age of Medalists by Sport',
    labels={'sport': 'Sport', 'age': 'Age'},
    color='age',
    color_continuous_scale=px.colors.sequential.Plasma
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Sport',
    yaxis_title='Age of Medalist'
)

fig.show()

In [ ]:
fig = px.histogram(
    medalists_age_df,
    x='age',
    nbins=20,
    title='Age Distribution of Olympic Medalists',
    labels={'age': 'Age of Medalist', 'count': 'Number of Medalists'},
    color_discrete_sequence=px.colors.sequential.Plasma
)

fig.update_layout(
    xaxis_title='Age of Medalist',
    yaxis_title='Number of Medalists'
)

fig.show()

In [ ]:
season_colors = {
    'Summer': 'red',
    'Winter': 'blue'
}

fig = px.bar(
    olympiad_summry_df.sort_values(by='games_year'),
    x='games_year',
    y='total_events',
    color='season',
    color_discrete_map=season_colors,
    title='Total Events per Olympic Games (by Year and Season)',
    labels={
        'games_year': 'Olympic Year',
        'total_events': 'Number of Total Events',
        'season': 'Olympic Season'
    },
    barmode='group'
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Olympic Year',
    yaxis_title='Number of Total Events',
    legend_title_text='Season'
)

fig.show()

In [ ]:
events_heatmap_data = olympiad_summry_df.pivot_table(
    index='host_country',
    columns='games_year',
    values='total_events',
    aggfunc='sum'
)

events_heatmap_data = events_heatmap_data.fillna(0)

fig = px.imshow(events_heatmap_data,
                labels=dict(x="Olympic Year", y="Host Country", color="Total Events"),
                x=events_heatmap_data.columns,
                y=events_heatmap_data.index,
                color_continuous_scale=px.colors.sequential.Plasma,
                title="Total Events per Host Country Across Olympic Years")

fig.update_xaxes(side="top")

fig.show()

In [ ]:
olympiad_summry_melted = olympiad_summry_df.melt(
    id_vars=['host_country', 'host_city', 'games_year'],
    value_vars=['number_of_gold_medals', 'number_of_silver_medals', 'number_of_bronze_medals'],
    var_name='medal_type',
    value_name='medal_count'
)

color_map = {
    'number_of_gold_medals': 'orange',
    'number_of_silver_medals': 'gray',
    'number_of_bronze_medals': 'brown'
}
olympiad_summry_melted['color'] = olympiad_summry_melted['medal_type'].map(color_map)

fig = px.bar(
    olympiad_summry_melted,
    x='host_country',
    y='medal_count',
    color='medal_type',
    color_discrete_map=color_map,
    title='Medal Distribution for Olympiad Sports According to Host Countries',
    labels={'host_country': 'Country', 'medal_count': 'Number of Medals', 'medal_type': 'Medal Type'},
    barmode='group',
    hover_data=['host_city', 'games_year']
)

fig.update_layout(
    xaxis_tickangle=-45,
    legend_title_text='Medal Type',
    xaxis_title='Host Country',
    yaxis_title='Number of Medals'
)

fig.show()

In [ ]:
comparison_status_df = olympiad_summry_df[[
    'games_year',
    'number_of_gold_medals',
    'total_medals',
    'athlete_with_most_medals',
    'athlete_with_most_medals_country',
    'athlete_with_most_gold_medals',
    'athlete_with_most_gold_medals_country'
]].copy()

comparison_status_df['athlete_match'] = (
    comparison_status_df['athlete_with_most_medals'] ==
    comparison_status_df['athlete_with_most_gold_medals']
)

comparison_status_df['country_match'] = (
    comparison_status_df['athlete_with_most_medals_country'] ==
    comparison_status_df['athlete_with_most_gold_medals_country']
)

def get_comparison_status(row):
    if row['athlete_match'] and row['country_match']:
        return 'Same Athlete & Country'
    elif row['athlete_match']:
        return 'Same Athlete, Different Country'
    elif row['country_match']:
        return 'Different Athlete, Same Country'
    else:
        return 'Different Athlete & Country'

comparison_status_df['comparison_status'] = comparison_status_df.apply(get_comparison_status, axis=1)

status_counts_per_year = comparison_status_df.groupby(['games_year','number_of_gold_medals', 'total_medals', 'comparison_status', 'athlete_with_most_medals', 'athlete_with_most_medals_country']).size().reset_index(name='count')

comparison_colors = {
    'Same Athlete & Country': 'mediumseagreen',
    'Different Athlete, Same Country': 'mediumblue',
    'Different Athlete & Country': 'red'
}

fig = px.bar(
    status_counts_per_year,
    x='games_year',
    y='count',
    color='comparison_status',
    color_discrete_map=comparison_colors,
    title='Comparison of Top Medalist (Overall) vs. Top Gold Medalist Across Olympic Years',
    labels={
        'games_year': 'Olympic Year',
        'count': 'Number of Olympic Games',
        'comparison_status': 'Comparison Status'
    },
    barmode='stack',
    hover_data={
        'games_year': True,
        'count': True,
        'comparison_status': True,
        'number_of_gold_medals': True,
        'total_medals': True,
        'athlete_with_most_medals': True,
        'athlete_with_most_medals_country': True
    }
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Olympic Year',
    yaxis_title='Number of Olympic Games',
    legend_title_text='Comparison Status'
)

fig.show()

In [ ]:
medal_trends_df = olympiad_summry_df.melt(
    id_vars=['games_year', 'season'],
    value_vars=['number_of_gold_medals', 'number_of_silver_medals', 'number_of_bronze_medals'],
    var_name='medal_type',
    value_name='medal_count'
)

medal_trends_df = medal_trends_df.sort_values(by='games_year')

medal_type_colors = {
    'number_of_gold_medals': 'gold',
    'number_of_silver_medals': 'silver',
    'number_of_bronze_medals': 'brown'
}

fig = px.line(
    medal_trends_df,
    x='games_year',
    y='medal_count',
    color='medal_type',
    color_discrete_map=medal_type_colors,
    title='Trends of Olympic Medals (Gold, Silver, Bronze) Over Time',
    labels={
        'games_year': 'Olympic Year',
        'medal_count': 'Number of Medals',
        'medal_type': 'Medal Type'
    },
    hover_data=['season']
)

fig.update_layout(
    xaxis_title='Olympic Year',
    yaxis_title='Number of Medals',
    legend_title_text='Medal Type'
)

fig.show()

In [ ]:
fig = px.scatter(
    olympiad_summry_df,
    x='total_events',
    y='total_medals',
    color='season',
    hover_name='host_city',
    hover_data=['games_year', 'host_country', 'total_events', 'total_medals', 'season'],
    title='Total Events vs. Total Medals by Olympic Year and Season',
    labels={
        'total_events': 'Number of Total Events',
        'total_medals': 'Total Number of Medals',
        'season': 'Olympic Season'
    },
    size='total_medals',
    color_discrete_map={'Summer': 'red', 'Winter': 'blue'}
)

fig.update_layout(
    xaxis_title='Number of Total Events',
    yaxis_title='Total Number of Medals',
    legend_title_text='Olympic Season'
)

fig.show()

In [ ]:
host_country_counts = olympiad_summry_df['host_country'].value_counts().reset_index()
host_country_counts.columns = ['host_country', 'number_of_times_hosted']

fig = px.bar(
    host_country_counts.sort_values(by='number_of_times_hosted', ascending=False),
    x='host_country',
    y='number_of_times_hosted',
    color='number_of_times_hosted',
    color_continuous_scale=px.colors.sequential.Viridis,
    title='Frequency of Olympic Games Hosted by Country',
    labels={
        'host_country': 'Host Country',
        'number_of_times_hosted': 'Number of Times Hosted'
    }
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Host Country',
    yaxis_title='Number of Times Hosted'
)

fig.show()

In [ ]:
fig = px.bar(
    sports_summry_df.sort_values(by='total_medals', ascending=False),
    x='discipline',
    y='total_medals',
    color='season',
    title='Total Medals per Discipline',
    labels={'discipline': 'Sport Discipline', 'total_medals': 'Total Number of Medals', 'season': 'Olympic Season'},
    hover_data=['number_of_gold_medals', 'number_of_silver_medals', 'number_of_bronze_medals']
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Sport Discipline',
    yaxis_title='Total Number of Medals',
    legend_title_text='Season'
)

fig.show()

In [ ]:
sports_medals_melted = sports_summry_df.melt(
    id_vars=['discipline', 'season'],
    value_vars=['number_of_gold_medals', 'number_of_silver_medals', 'number_of_bronze_medals'],
    var_name='medal_type',
    value_name='medal_count'
)

medal_colors = {
    'number_of_gold_medals': 'gold',
    'number_of_silver_medals': 'silver',
    'number_of_bronze_medals': 'brown'
}

fig = px.bar(
    sports_medals_melted,
    x='discipline',
    y='medal_count',
    color='medal_type',
    color_discrete_map=medal_colors,
    title='Medal Distribution (Gold, Silver, Bronze) per Discipline',
    labels={'discipline': 'Sport Discipline', 'medal_count': 'Number of Medals', 'medal_type': 'Medal Type'},
    barmode='group',
    hover_data=['season']
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Sport Discipline',
    yaxis_title='Number of Medals',
    legend_title_text='Medal Type'
)

fig.show()

In [ ]:
fig = px.bar(
    sports_summry_df.sort_values(by='number_of_olympics', ascending=False),
    x='discipline',
    y='number_of_olympics',
    color='season',
    title='Number of Olympic Games Appearances per Discipline',
    labels={'discipline': 'Sport Discipline', 'number_of_olympics': 'Number of Olympic Appearances', 'season': 'Olympic Season'}
)

fig.update_layout(
    xaxis_tickangle=-45,
    xaxis_title='Sport Discipline',
    yaxis_title='Number of Olympic Appearances',
    legend_title_text='Season'
)

fig.show()

In [ ]:
fig = px.scatter(
    sports_summry_df,
    x='number_of_olympics',
    y='total_medals',
    color='season',
    size='total_medals',
    hover_name='discipline',
    hover_data=['number_of_gold_medals', 'number_of_silver_medals', 'number_of_bronze_medals'],
    title='Number of Olympic Appearances vs. Total Medals per Discipline',
    labels={'number_of_olympics': 'Number of Olympic Appearances', 'total_medals': 'Total Number of Medals', 'season': 'Olympic Season'}
)

fig.update_layout(
    xaxis_title='Number of Olympic Appearances',
    yaxis_title='Total Number of Medals',
    legend_title_text='Season'
)

fig.show()