<a href="https://colab.research.google.com/github/abdelhalimyasser/Olympics-Data-Pipeline-AI-Classification/blob/main/nootbooks/wikipedia_olympic_medalists_webscrapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://en.wikipedia.org/wiki/Lists_of_Olympic_medalists"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
}

response = requests.get(url, headers=headers)

In [4]:
# get all the data in a soup
soup = BeautifulSoup(response.text, 'html.parser')

In [5]:
# get all the tabels
found_table = soup.find_all("table", {'class':"wikitable"})

In [6]:
# get summer olympic sports
summer_olympic_sports = found_table[0]

summer_olympic_sports_data = []

rows = summer_olympic_sports.find_all('tr')

for row in rows:
    cells = row.find_all('td')
    if len(cells) >= 9:
        summer_sports_medalist_by_sport = {
            'discipline':                    cells[0].text.strip(),
            'contestes':                     cells[1].text.strip(),
            'number_of_olympics':            cells[2].text.strip(),
            'number_of_medals':              cells[3].text.strip(),
            'number_of_gold_medals':         cells[4].text.strip(),
            'number_of_silver_medals':       cells[5].text.strip(),
            'number_of_bronze_medals':       cells[6].text.strip(),
            'total':                         cells[7].text.strip(),
            'athlete_with_most_medals':      cells[8].text.strip(),
            'athlete_with_most_gold_medals': cells[9].text.strip()
        }

        summer_olympic_sports_data.append(summer_sports_medalist_by_sport)

In [7]:
# get winter olympic sports
winter_olympic_sports = found_table[1]

winter_olympic_sports_data = []

rows = winter_olympic_sports.find_all('tr')

for row in rows:
    cells = row.find_all('td')
    if len(cells) >= 9:
        winter_sports_medalist_by_sport = {
            'discipline':                    cells[0].text.strip(),
            'contestes':                     cells[1].text.strip(),
            'number_of_olympics':            cells[2].text.strip(),
            'number_of_medals':              cells[3].text.strip(),
            'number_of_gold_medals':         cells[4].text.strip(),
            'number_of_silver_medals':       cells[5].text.strip(),
            'number_of_bronze_medals':       cells[6].text.strip(),
            'total':                         cells[7].text.strip(),
            'athlete_with_most_medals':      cells[8].text.strip(),
            'athlete_with_most_gold_medals': cells[9].text.strip()
        }

        winter_olympic_sports_data.append(winter_sports_medalist_by_sport)

In [8]:
# get discontiued summer sports
discontinued_summer_sports = found_table[2]

discontinued_summer_sports_data = []

rows = discontinued_summer_sports.find_all('tr')

for row in rows:
    cells = row.find_all('td')
    if len(cells) >= 6:
      discontinued_summer_sports = {
            'discipline':                    cells[0].text.strip(),
            'contestes':                     cells[1].text.strip(),
            'number_of_olympics':            cells[2].text.strip(),
            'number_of_gold_medals':         cells[3].text.strip(),
            'number_of_silver_medals':       cells[4].text.strip(),
            'number_of_bronze_medals':       cells[5].text.strip(),
            'total':                         cells[6].text.strip()
            }

      discontinued_summer_sports_data.append(discontinued_summer_sports)

In [9]:
# get summer olympic olympiad
summer_olympiad = found_table[3]

summer_olympiad_data = []

rows = summer_olympiad.find_all('tr')

for row in rows:
    cells = row.find_all('td')
    if len(cells) >= 11:
       summer_sports_medalist_by_olympiad = {
           'games':                         cells[0].text.strip(),
           'medal_winners':                 cells[1].text.strip(),
           'medal_table':                   cells[2].text.strip(),
           'host':                          cells[3].text.strip(),
           'number_medal_events':           cells[4].text.strip(),
           'number_of_gold_medals':         cells[5].text.strip(),
           'number_of_silver_medals':       cells[6].text.strip(),
           'number_of_bronze_medals':       cells[7].text.strip(),
           'total':                         cells[8].text.strip(),
           'athlete_with_most_medals':      cells[9].text.strip(),
           'athlete_with_most_gold_medals': cells[10].text.strip()
       }

       summer_olympiad_data.append(summer_sports_medalist_by_olympiad)

In [10]:
# get winter olympic olympiad
winter_olympiad = found_table[4]

winter_olympiad_data = []

rows = winter_olympiad.find_all('tr')

for row in rows:
    cells = row.find_all('td')
    if len(cells) >= 11:
       winter_sports_medalist_by_olympiad = {
           'games':                         cells[0].text.strip(),
           'medal_winners':                 cells[1].text.strip(),
           'medal_table':                   cells[2].text.strip(),
           'host':                          cells[3].text.strip(),
           'number_medal_events':           cells[4].text.strip(),
           'number_of_gold_medals':         cells[5].text.strip(),
           'number_of_silver_medals':       cells[6].text.strip(),
           'number_of_bronze_medals':       cells[7].text.strip(),
           'total':                         cells[8].text.strip(),
           'athlete_with_most_medals':      cells[9].text.strip(),
           'athlete_with_most_gold_medals': cells[10].text.strip()
       }

       winter_olympiad_data.append(winter_sports_medalist_by_olympiad)

In [11]:
# get medalists age by sport
medalists_age_by_sport = found_table[5]

medalists_age_by_sport_data = []
current_sport = ""

rows = medalists_age_by_sport.find_all('tr')

for row in rows:
    sport_header = row.find('th', colspan="5")
    if sport_header:
        current_sport = sport_header.get_text(strip=True)
        continue

    cells = row.find_all('td')
    if len(cells) >= 4:
       row_data = {
           'sport':    current_sport,
           'title':    cells[0].get_text(separator=' ', strip=True),
           'age':      cells[1].get_text(separator=' ', strip=True),
           'medalist': cells[2].get_text(separator=' ', strip=True),
           'details':  cells[3].get_text(separator=' ', strip=True),
           'notes':    cells[4].get_text(separator=' ', strip=True) if len(cells) >= 5 else "",
       }

       medalists_age_by_sport_data.append(row_data)

In [12]:
# convert into dataframes
summer_sports_medalist_by_sport_df    = pd.DataFrame(summer_olympic_sports_data)
winter_sports_medalist_by_sport_df    = pd.DataFrame(winter_olympic_sports_data)
discontinued_summer_sports_df         = pd.DataFrame(discontinued_summer_sports_data)
summer_sports_medalist_by_olympiad_df = pd.DataFrame(summer_olympiad_data)
winter_sports_medalist_by_olympiad_df = pd.DataFrame(winter_olympiad_data)
medalists_age_by_sport_df             = pd.DataFrame(medalists_age_by_sport_data)

In [13]:
# convert into csv files
summer_sports_medalist_by_sport_df.to_csv('summer_sports_medalist_by_sport.csv', index=False)
winter_sports_medalist_by_sport_df.to_csv('winter_sports_medalist_by_sport.csv', index=False)
discontinued_summer_sports_df.to_csv('discontinued_summer_sports.csv', index=False)
summer_sports_medalist_by_olympiad_df.to_csv('summer_sports_medalist_by_olympiad.csv', index=False)
winter_sports_medalist_by_olympiad_df.to_csv('winter_sports_medalist_by_olympiad.csv', index=False)
medalists_age_by_sport_df.to_csv('medalists_age_by_sport.csv', index=False)

In [14]:
summer_sports_medalist_by_sport_df.head(2)

,discipline,contestes,number_of_olympics,number_of_medals,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total,athlete_with_most_medals,athlete_with_most_gold_medals
0,Archery,1900–1908; 1920; since 1972,18,5,76,74,66,216,Hubert van Innis (BEL) (6–3–0),Hubert van Innis (BEL) (6–3–0)
1,Artistic swimming,Since 1984,11,2,22,20,21,63,Svetlana Romashina (RUS) (7–0–0) Huang Xuechen...,Svetlana Romashina (RUS) (7–0–0)

In [15]:
winter_sports_medalist_by_sport_df.head(2)

,discipline,contestes,number_of_olympics,number_of_medals,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total,athlete_with_most_medals,athlete_with_most_gold_medals
0,Alpine skiing,Since 1936,22,10,175,178,171,524,Kjetil André Aamodt (NOR) (4–2–2),Kjetil André Aamodt (NOR) (4–2–2) Janica Koste...
1,Biathlon,1924[a];since 1960,22,11,108,108,106,355,Ole Einar Bjørndalen (NOR) (8–4–2),Ole Einar Bjørndalen (NOR) (8–4–2)

In [16]:
discontinued_summer_sports_df.head(2)

,discipline,contestes,number_of_olympics,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total
0,Basque pelota,1900,1,1,0,0,1
1,Breaking,2024,1,2,2,2,6

In [17]:
summer_sports_medalist_by_olympiad_df.head(2)

,games,medal_winners,medal_table,host,number_medal_events,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total,athlete_with_most_medals,athlete_with_most_gold_medals
0,1896,winners,table,"Athens, Greece",43,43,43,36,122,Hermann Weingärtner (GER) (3–2–1),Carl Schuhmann (GER) (4–0–0)
1,1900,winners,table,"Paris, France",95[d],96,95,93,284,Irving Baxter (USA) (2–3–0) Walter Tewksbury (...,Alvin Kraenzlein (USA) (4–0–0)

In [18]:
winter_sports_medalist_by_olympiad_df.head(2)

,games,medal_winners,medal_table,host,number_medal_events,number_of_gold_medals,number_of_silver_medals,number_of_bronze_medals,total,athlete_with_most_medals,athlete_with_most_gold_medals
0,1924,winners,table,"Chamonix, France",16,16,16,17,49,Clas Thunberg (FIN) (3–1–1) Roald Larsen (NOR)...,Clas Thunberg (FIN) (3–1–1) Thorleif Haug (NOR...
1,1928,winners,table,"St. Moritz, Switzerland",14,14,12,15,41,Bernt Evensen (NOR) (1–1–1),Johan Grøttumsbraaten (NOR) (2–0–0) Clas Thunb...

In [19]:
medalists_age_by_sport_df.head(2)

,sport,title,age,medalist,details,notes
0,Freestyle skiing,Youngest freestyle skiing medalist,18 years 158 days,Ailing Eileen Gu,,
1,Freestyle skiing,Youngest freestyle skiing gold medalist,18 years 158 days,Ailing Eileen Gu,,